server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc: # <-- CRITICAL EXACT PATH FOR BOOT 4 / CLOUD 2025

          cors:
             cors-configurations:
               '[/**]':
                 allowed-origins:
                   - "http://localhost:5173"
                 allowed-methods:
                   - GET
                   - POST
                   - PUT
                   - DELETE
                   - OPTIONS
                 allowed-headers:
                   - "*"
                 allow-credentials: true
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**

            - id: patient-service
              uri: lb://PATIENT-SERVICE
              predicates:
                - Path=/api/v1/patient/**

            - id: doctor-service
              uri: lb://DOCTOR-SERVICE
              predicates:
                - Path=/api/v1/doctor/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG